"""Compatibility facade for modular stage evaluation policies.

Production code should continue importing from :mod:`toc.stage_evaluator`.
Implementation ownership lives under :mod:`toc.stage_evaluation`.
"""

from toc.harness import load_structured_document

from toc.stage_evaluation.common import (
    SCENE_COVERAGE_REVIEW_REQUIRED_KEYS,
    _append_grounding_checks,
    add_check,
    as_dict,
    as_dotted_str,
    as_int,
    as_list,
    contract_list,
    detect_flow,
    flatten_text,
    flatten_without_keys,
    has_todo,
    make_stage,
    nested_get,
    non_empty,
    scene_time_of_day_contract_marker,
    scene_time_of_day_contract_missing,
    scene_time_of_day_visual_basis_contract_marker,
    scene_time_of_day_visual_basis_issues,
    score_from_checks,
    score_from_ratio,
)
from toc.stage_evaluation.manifest import (
    _manifest_checks,
    _minimum_cut_issues,
    check_manifest_scene_series,
    check_manifest_single,
)
from toc.stage_evaluation.research_story import (
    _image_api_prompt_v2_issues,
    _manifest_rubric,
    check_research,
    check_story,
    check_visual_value,
    compact_research_pack_ok,
    dense_story_scene_count,
    story_scene_coverage_ok,
)
from toc.stage_evaluation.runner import (
    append_stage_review_state,
    evaluate_stage,
    render_stage_review,
)
from toc.stage_evaluation.script import (
    _cinematic_min_cuts_for_scene,
    _coverage_authored_obligation_ids,
    _coverage_minimum_cut_count,
    _cut_event_ref_issue_map,
    _scene_cut_coverage_plan_issues,
    _scene_cut_redundancy_issues,
    _scene_event_issue_map,
    _scene_readiness_issues,
    check_script_scene_series,
    check_script_single,
)
from toc.stage_evaluation.video import (
    check_video_scene_series,
    check_video_single,
)

__all__ = [
    "SCENE_COVERAGE_REVIEW_REQUIRED_KEYS",
    "_append_grounding_checks",
    "_cinematic_min_cuts_for_scene",
    "_coverage_authored_obligation_ids",
    "_coverage_minimum_cut_count",
    "_cut_event_ref_issue_map",
    "_image_api_prompt_v2_issues",
    "_manifest_checks",
    "_manifest_rubric",
    "_minimum_cut_issues",
    "_scene_cut_coverage_plan_issues",
    "_scene_cut_redundancy_issues",
    "_scene_event_issue_map",
    "_scene_readiness_issues",
    "add_check",
    "append_stage_review_state",
    "as_dict",
    "as_dotted_str",
    "as_int",
    "as_list",
    "check_manifest_scene_series",
    "check_manifest_single",
    "check_research",
    "check_script_scene_series",
    "check_script_single",
    "check_story",
    "check_video_scene_series",
    "check_video_single",
    "check_visual_value",
    "compact_research_pack_ok",
    "contract_list",
    "dense_story_scene_count",
    "detect_flow",
    "evaluate_stage",
    "flatten_text",
    "flatten_without_keys",
    "has_todo",
    "load_structured_document",
    "make_stage",
    "nested_get",
    "non_empty",
    "render_stage_review",
    "scene_time_of_day_contract_marker",
    "scene_time_of_day_contract_missing",
    "scene_time_of_day_visual_basis_contract_marker",
    "scene_time_of_day_visual_basis_issues",
    "score_from_checks",
    "score_from_ratio",
    "story_scene_coverage_ok",
]
